# Generated by Django 3.1.7 on 2021-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('bat_hand', models.CharField(max_length=200, null=True)),
                ('bowl_skill', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
